# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://kai-tub.github.io/dummy/"

git_url = "https://github.com/kai-tub/dummy/tree/main/"

def custom_doc_links(name): return None
